integration_dt: 0.1
damping: 1e-9
Kpos: 0.95
Kori: 0.95
gravity_compensation: true
dt: 0.008
Kn: [10.0, 10.0, 10.0, 10.0, 5.0, 5.0, 5.0]
max_angvel: 2.0

xml_path: "franka_emika_panda/scene.xml"
site_name: "attachment_site"
joint_names:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
actuator_names:
  - actuator1
  - actuator2
  - actuator3
  - actuator4
  - actuator5
  - actuator6
  - actuator7
key_name: "home"
mocap_name: "target"
